const data = [
    {
        id: 1,
        topName: 'Banana Bliss: Indulge in Irresistible',
        bottomName: 'Homemade Banana Bread',
        price: 1099,
        ingredients: "Butter, sugar, light brown sugar, eggs, vanilla extract, milk, flour, baking soda, cinnamon, and salt",
        img: require(`./images/banana bread.jpg`),
        alt: 'Homemade Banana Bread',
        quantity: 1,
    }, 
    {
        id: 2,
        topName: 'Tres Leches Delight: Experience the Perfection of',
        bottomName: 'Homemade Tres Leches Cake',
        price: 2599,
        ingredients: "Whip cream, sugar, biscoff biscuit crumbs, caramel, and cake mix",
        img: require(`./images/tresleches.jpg`),
        alt: 'Homemade Tres Leches Cake',
        quantity: 1,
    }, 
    {
        id: 3,
        topName: 'Cookies Galore: Delight in a Scrumptious Array of',
        bottomName: 'Homemade Cookies',
        price: 1099,
        ingredients: "Butter, light brown sugar, sugar, egg, vanilla extract, flour, bicorbonate of soda, salt, and chocolate chips",
        img: require(`./images/cookie.jpg`),
        alt: 'Homemade Cookies',
        quantity: 1,
    }, 
    {
        id: 4,
        topName: 'Cinnamon Delight: Indulge in the Irresistible Aroma of',
        bottomName: 'Homemade Cinnamon Bread',
        price: 1099,
        ingredients: "Light brown sugar, cinnamon, butter, flour, sugar, baking powder, eggs, milk, vanilla extract, and bananas",
        img: require(`./images/cinnamon bread.jpg`),
        alt: 'Homemade Cinnamon Bread',
        quantity: 1,
    },  
    {
        id: 5,
        topName: 'Sweetness in Every Bite: Discover the Joy of Our Irresistible',
        bottomName: 'Homemade Cupcakes',
        price: 799,
        ingredients: "Cake mix, eggs, oil, water, and butter",
        img: require(`./images/cupcakes.jpg`),
        alt: 'Homemade Cupcakes',
        quantity: 1,
    },  
]

export default data